const KEY='offline_contact_payment_v1';let contacts=[];let headers=[];let years=[];
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify({contacts,headers,years}))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');contacts=x.contacts||[];headers=x.headers||[];years=x.years||[]}catch(e){}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function isYear(h){return /^(19|20)\d{2}$/.test(String(h).trim())}
function unpaid(c){return years.filter(y=>String(c.data[y]??'').trim()==='')}
function renderFilters(){const s=$('yearFilter');s.innerHTML='<option value="all">All unpaid years</option>'+years.map(y=>`<option value="${y}">${y}</option>`).join('')}
function render(){const q=$('search').value.trim().toLowerCase(),yf=$('yearFilter').value;let arr=contacts.filter(c=>(!q||c.name.toLowerCase().includes(q)||c.phone.toLowerCase().includes(q))&&(yf==='all'||unpaid(c).includes(yf)));$('summary').textContent=`${arr.length} shown • ${contacts.length} total`;if(!arr.length){$('list').innerHTML='<div class="empty">No contacts found.<br>Import an Excel file to begin.</div>';return}$('list').innerHTML=arr.map(c=>{const u=unpaid(c),p=u.length===0;return `<article class="card ${c.called?'called':''}"><div class="top"><div><div class="name">${esc(c.name||'Unnamed')}</div><div class="phone">${esc(c.phone)}</div></div><div class="status ${p?'paid':'unpaid'}">${p?'PAID':'NOT PAID'}</div></div>${p?'':'<div class="years">'+u.map(y=>`<span class="year">${y}</span>`).join('')+'</div>'}<div class="actions"><button class="call" onclick="callNumber('${esc(c.phone)}')">📞 CALL</button><button onclick="toggleCalled('${encodeURIComponent(c.phone)}')">${c.called?'✓ CALLED':'Mark Called'}</button></div></article>`}).join('')}
function callNumber(p){location.href='tel:'+String(p).replace(/[^\d+]/g,'')}
function toggleCalled(ep){const p=decodeURIComponent(ep);const c=contacts.find(x=>x.phone===p);if(c){c.called=!c.called;c.calledAt=c.called?new Date().toLocaleString():'';save();render()}}
async function readZip(buf){const b=new Uint8Array(buf),dv=new DataView(buf);let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--){if(dv.getUint32(i,true)===0x06054b50){eocd=i;break}}if(eocd<0)throw Error('Invalid XLSX/ZIP file');const cdSize=dv.getUint32(eocd+12,true),cdOff=dv.getUint32(eocd+16,true);let p=cdOff,files={};while(p<cdOff+cdSize){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),cs=dv.getUint32(p+20,true),us=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),el=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),off=dv.getUint32(p+42,true);const name=new TextDecoder().decode(b.slice(p+46,p+46+nl));files[name]={method,cs,us,off};p+=46+nl+el+cl}async function get(name){const f=files[name];if(!f)throw Error('Missing '+name);const q=f.off;const n=dv.getUint16(q+26,true),m=dv.getUint16(q+28,true),start=q+30+n+m;const raw=b.slice(start,start+f.cs);if(f.method===0)return raw;if(f.method===8){const ds=new DecompressionStream('deflate-raw');return new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(ds)).arrayBuffer())}throw Error('Unsupported compression')}return {files,get}}
function xmlDoc(bytes){return new DOMParser().parseFromString(new TextDecoder().decode(bytes),'application/xml')}
async function parseXlsx(buf){const z=await readZip(buf),shared=[];if(z.files['xl/sharedStrings.xml']){const d=xmlDoc(await z.get('xl/sharedStrings.xml'));d.querySelectorAll('si').forEach(si=>shared.push(Array.from(si.querySelectorAll('t')).map(x=>x.textContent).join('')))}let sheet='xl/worksheets/sheet1.xml';if(!z.files[sheet]){const names=Object.keys(z.files).filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x));if(!names.length)throw Error('No worksheet found');sheet=names[0]}const d=xmlDoc(await z.get(sheet));const rows=[];d.querySelectorAll('sheetData > row').forEach(r=>{const vals=[];r.querySelectorAll(':scope > c').forEach(c=>{const ref=c.getAttribute('r')||'';const m=ref.match(/([A-Z]+)\d+/);if(!m)return;let col=0;for(const ch of m[1])col=col*26+ch.charCodeAt(0)-64;col--;while(vals.length<col)vals.push('');let v=c.querySelector('v')?.textContent??'';if(c.getAttribute('t')==='s')v=shared[Number(v)]??'';else if(c.getAttribute('t')==='inlineStr')v=Array.from(c.querySelectorAll('t')).map(x=>x.textContent).join('');vals[col]=v});rows.push(vals)});return rows}
async function importFile(file){const rows=await parseXlsx(await file.arrayBuffer());if(!rows.length)throw Error('Empty worksheet');headers=rows[0].map(x=>String(x).trim());const lower=headers.map(x=>x.toLowerCase());const ni=lower.findIndex(x=>['name','full name','candidate name'].includes(x));const pi=lower.findIndex(x=>['contact','phone','mobile','mobile no','phone number','contact number'].includes(x));if(pi<0)throw Error('Contact/Phone/Mobile column not found');years=headers.filter(isYear);if(!years.length)throw Error('No year columns found, e.g. 2022, 2023, 2024, 2025');contacts=rows.slice(1).filter(r=>r.some(v=>String(v??'').trim()!=='')).map(r=>{const data={};headers.forEach((h,i)=>data[h]=String(r[i]??'').trim());return{name:ni>=0?String(r[ni]??'').trim():'',phone:String(r[pi]??'').trim(),data,called:false,calledAt:''}});save();renderFilters();render()}
$('importBtn').onclick=()=>$('file').click();$('file').onchange=async e=>{try{await importFile(e.target.files[0]);alert(`Imported ${contacts.length} contacts.`)}catch(err){alert('Import failed: '+err.message)}e.target.value=''};$('search').oninput=render;$('yearFilter').onchange=render;$('clearBtn').onclick=()=>{if(confirm('Delete all imported data from this phone?')){localStorage.removeItem(KEY);contacts=[];headers=[];years=[];renderFilters();render()}};load();renderFilters();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
